name: Deploy Call Assistant Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

env:
  AWS_REGION: us-west-1
  STACK_NAME: call-assistant

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies and package Lambda
      run: |
        cd backend
        
        # Create deployment package directory
        mkdir -p lambda-package
        
        # Install dependencies to package directory
        pip install -r requirements.txt -t lambda-package/
        
        # Copy application code
        cp *.py lambda-package/
        cp -r routers/ lambda-package/ 2>/dev/null || echo "No routers directory"
        cp -r services/ lambda-package/ 2>/dev/null || echo "No services directory"
        
        # Create zip file
        cd lambda-package
        zip -r ../lambda.zip . -x "*.pyc" "*__pycache__*" "*.git*"
        cd ..
        
        # Verify zip file
        echo "Lambda package size: $(du -h lambda.zip)"
        echo "Lambda package contents:"
        unzip -l lambda.zip | head -20

    - name: Upload Lambda package to S3
      run: |
        aws s3 cp backend/lambda.zip s3://${{ secrets.LAMBDA_S3_BUCKET }}/lambda.zip
        echo "✅ Lambda package uploaded to S3"

    - name: Generate CloudFormation template
      run: |
        cd iac
        python generate_template.py > template.yml
        echo "✅ CloudFormation template generated"

    - name: Deploy CloudFormation stack
      run: |
        cd iac
        
        # Deploy or update stack
        aws cloudformation deploy \
          --template-file template.yml \
          --stack-name ${{ env.STACK_NAME }} \
          --parameter-overrides \
            LambdaS3Bucket=${{ secrets.LAMBDA_S3_BUCKET }} \
            LambdaS3Key=lambda.zip \
            FrontendS3Bucket=${{ secrets.FRONTEND_S3_BUCKET }} \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset
        
        echo "✅ CloudFormation deployment completed"

    - name: Get deployment outputs
      run: |
        echo "🚀 Deployment Summary:"
        aws cloudformation describe-stacks \
          --stack-name ${{ env.STACK_NAME }} \
          --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
          --output table || echo "No outputs available yet"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd web
        npm ci

    - name: Build frontend
      run: |
        cd web
        npm run build
        echo "✅ Frontend built successfully"

    - name: Deploy frontend to S3
      run: |
        cd web
        
        # Sync the built files to S3
        if [ -d "out" ]; then
          # Next.js static export
          aws s3 sync out/ s3://${{ secrets.FRONTEND_S3_BUCKET }}/ --delete
          echo "✅ Frontend deployed from 'out' directory"
        elif [ -d ".next" ]; then
          # Next.js build (need to handle this differently for static hosting)
          echo "⚠️  Next.js server build detected. Configure static export in next.config.js"
          echo "For S3 hosting, add: output: 'export' to next.config.js"
        elif [ -d "dist" ]; then
          # Vite/other build tools
          aws s3 sync dist/ s3://${{ secrets.FRONTEND_S3_BUCKET }}/ --delete
          echo "✅ Frontend deployed from 'dist' directory"
        elif [ -d "build" ]; then
          # Create React App build
          aws s3 sync build/ s3://${{ secrets.FRONTEND_S3_BUCKET }}/ --delete
          echo "✅ Frontend deployed from 'build' directory"
        else
          echo "❌ No build output directory found"
          exit 1
        fi
        
        # Invalidate CloudFront cache to see changes immediately
        DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name ${{ env.STACK_NAME }} \
          --query 'Stacks[0].Outputs[?OutputKey==`FrontendDistributionId`].OutputValue' \
          --output text 2>/dev/null || echo "")
        
        if [ -n "$DISTRIBUTION_ID" ]; then
          echo "🔄 Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
          echo "✅ CloudFront cache invalidated"
        else
          echo "ℹ️  CloudFront distribution ID not found in outputs"
        fi

