name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      LAMBDA_S3_BUCKET: ${{ secrets.LAMBDA_S3_BUCKET }}
      LAMBDA_S3_KEY: ${{ secrets.LAMBDA_S3_KEY }}
      CLOUDFRONT_ORIGIN_DOMAIN: ${{ secrets.CLOUDFRONT_ORIGIN_DOMAIN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install -r requirements.txt

      - name: Compile backend
        run: python -m py_compile backend/*.py

      - name: Install frontend dependencies
        run: |
          cd web
          npm install
          npm run type-check

      - name: Generate CloudFormation template
        run: |
          python iac/generate_template.py > template.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --template-file template.yml --stack-name call-assistant

